#!/usr/bin/env bash
set -Eeuo pipefail

BASE="https://sifappayload.blob.core.windows.net/payload"
STAGE=/opt/sifap/payload
CORPUS=/opt/sifap/corpus
PROVISIONING=/opt/sifap/provisioning
# Any version from 2017-11-09 onwards accepts an Entra bearer token; older
# ones only understand shared-key auth and answer 400.
BLOB_API=2021-08-06

rm -f /opt/sifap/PAYLOAD-FAILED
mkdir -p "$STAGE"

echo "--- payload: $BASE"

# One token, reused for every blob. Role assignments are eventually
# consistent, so the FIRST request is the one that legitimately 403s while
# "Storage Blob Data Reader" replicates - hence the retry loop rather than
# a hard failure.
TOKEN=""
for attempt in $(seq 1 30); do
  # -s keeps the token off stdout; it is never echoed or written to disk.
  TOKEN=$(curl -s --retry 3 --retry-delay 2 -H "Metadata:true" \
    "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fstorage.azure.com%2F" \
    | jq -r '.access_token // empty')

  if [ -n "$TOKEN" ] && curl -sSf --max-time 30 \
       -H "Authorization: Bearer $TOKEN" -H "x-ms-version: $BLOB_API" \
       -o "$STAGE/manifest.sha256" "$BASE/manifest.sha256"; then
    echo "manifest downloaded on attempt $attempt"
    break
  fi

  echo "payload not readable yet (attempt $attempt/30); retrying"
  TOKEN=""
  sleep 10
done

if [ ! -s "$STAGE/manifest.sha256" ]; then
  echo "############################################################"
  echo "ERROR: could not read $BASE/manifest.sha256"
  echo "ERROR: the corpus and the provisioning scripts will be MISSING."
  echo "ERROR: almost always one of:"
  echo "ERROR:   - the VM identity has no 'Storage Blob Data Reader' on the"
  echo "ERROR:     payload container (var.assign_vm_blob_role = false, or the"
  echo "ERROR:     assignment has not replicated yet - wait and re-run)"
  echo "ERROR:   - the storage account firewall is blocking this VM"
  echo "ERROR: re-run after fixing:  sudo /opt/sifap/fetch-payload.sh"
  echo "############################################################"
  date -Is > /opt/sifap/PAYLOAD-FAILED
  logger -t sifap-payload -p user.err "SIFAP-PAYLOAD RESULT: FAILED (manifest unreadable)" || true
  exit 1
fi

# The manifest is sha256sum(1) format, so it is both the file list and the
# integrity check. Names are generated by Terraform from a fileset and
# never contain spaces; anything that does is rejected rather than guessed.
COUNT=0
while read -r _hash name; do
  [ -n "$name" ] || continue
  case "$name" in
    *' '*|/*|*..*)
      echo "ERROR: refusing suspicious manifest entry: $name"
      exit 1
      ;;
  esac
  mkdir -p "$STAGE/$(dirname "$name")"
  curl -sSf --retry 3 --retry-delay 2 --max-time 120 \
    -H "Authorization: Bearer $TOKEN" -H "x-ms-version: $BLOB_API" \
    -o "$STAGE/$name" "$BASE/$name"
  COUNT=$((COUNT + 1))
done < "$STAGE/manifest.sha256"

echo "downloaded $COUNT files; verifying checksums"
( cd "$STAGE" && sha256sum -c --quiet manifest.sha256 )
echo "checksums OK"

# --- install ---------------------------------------------------------
# The corpus is bind-mounted read-only into natural-ce, which runs as uid
# 1724, so it has to be world-readable. It is published source code, not a
# secret.
mkdir -p "$CORPUS"
if [ -d "$STAGE/corpus" ]; then
  cp -a "$STAGE/corpus/." "$CORPUS/"
  chmod -R a+rX "$CORPUS"
  echo "corpus installed:"
  find "$CORPUS" -mindepth 1 -maxdepth 1 -type d -printf '  %f: ' -exec sh -c 'ls -1 "$1" | wc -l' _ {} \;
else
  echo "WARNING: the payload carried no corpus/ prefix - Adabas will have no SIFAP data."
fi

if [ -d "$STAGE/provisioning" ]; then
  mkdir -p "$PROVISIONING"
  cp -a "$STAGE/provisioning/." "$PROVISIONING/"
  # Blobs carry no mode bits, so executability is restored here. Both
  # extensions matter: 01-load-adabas.sh calls adacmp_input.py directly.
  find "$PROVISIONING" \( -name '*.sh' -o -name '*.py' \) -exec chmod 0755 {} +
  echo "provisioning scripts installed: $(find "$PROVISIONING" -name '*.sh' | wc -l) shell scripts"
else
  echo "############################################################"
  echo "WARNING: the payload carried no provisioning/ prefix."
  echo "WARNING: the corpus is on the VM but NOTHING WILL LOAD IT:"
  echo "WARNING: no Adabas file 150, no compiled SIFAPPRD library."
  echo "WARNING: infra/adabas-natural-lab/provisioning/ was empty at apply"
  echo "WARNING: time. Add the scripts, re-apply, then on the VM run:"
  echo "WARNING:   sudo /opt/sifap/fetch-payload.sh"
  echo "WARNING:   sudo systemctl restart sifap-provisioning"
  echo "############################################################"
fi

date -Is > /opt/sifap/PAYLOAD-OK
logger -t sifap-payload -p user.notice "SIFAP-PAYLOAD RESULT: SUCCESS ($COUNT files)" || true
echo "--- payload complete"
